using UnityEngine;

public class SanitySystem : MonoBehaviour
{
    public static SanitySystem Instance;

    [Header("ConfiguraÃ§Ãµes de Sanidade")]
    public float sanity = 100f;
    public float baseDecayRate = 0.05f;        // perda natural por segundo
    public float anomalyDecayMultiplier = 2f; // cada anomalia ativa acelera essa taxa
    public float currentDecayMultiplier = 1f;   // multiplicador dinÃ¢mico

    [Header("Modificadores TemporÃ¡rios")]
    public float reportEffectDuration = 100f;     // duraÃ§Ã£o do efeito de aceleraÃ§Ã£o/desaceleraÃ§Ã£o
    private float reportEffectTimer = 0f;

    [Header("Sanidade InstantÃ¢nea")]
    public float wrongReportPenalty = 15f;

    [Header("PÃ­lula")]
    public float pillRecoveryAmount = 40f;
    public int maxPills = 3;
    private int pillsUsed = 0;

    [Header("ReferÃªncias")]
    public AnomalyManager anomalyManager;

    private void Awake()
    {
        Instance = this;
    }

    private void Update()
    {
        // tempo do efeito de report
        if (reportEffectTimer > 0)
        {
            reportEffectTimer -= Time.deltaTime;
            if (reportEffectTimer <= 0)
            {
                currentDecayMultiplier = 1f; // volta ao normal
            }
        }

        int activeAnomalies = anomalyManager.GetActiveAnomalyCount();

        // cÃ¡lculo da taxa total de decaimento
        float totalDecay = (baseDecayRate + (activeAnomalies * anomalyDecayMultiplier)) * currentDecayMultiplier;

        // aplica o decaimento
        sanity -= totalDecay * Time.deltaTime;
        sanity = Mathf.Clamp(sanity, 0f, 100f);


        if (sanity <= 0f)
        {
            Debug.Log("ðŸ’€ SANIDADE ZERO â€” Game Over!");
            // tela de game over
        }
    }

    public void ReportCorrect()
    {
        currentDecayMultiplier = 0.5f; // desacelera
        reportEffectTimer = reportEffectDuration;
        Debug.Log("âœ… Reporte correto â€” decaimento desacelerado temporariamente!");
    }

    public void ReportWrong()
    {
        sanity -= wrongReportPenalty;
        sanity = Mathf.Clamp(sanity, 0f, 100f);
        currentDecayMultiplier = 2f;
        reportEffectTimer = reportEffectDuration;
        Debug.Log("âŒ Reporte incorreto â€” decaimento acelerado temporariamente!");
    }

    public void TakePill()
    {
    if (pillsUsed >= maxPills)
    {
        Debug.Log("ðŸ’Š Limite de pÃ­lulas atingido!");
        return;
    }

    sanity += pillRecoveryAmount;
    sanity = Mathf.Clamp(sanity, 0f, 100f);
    pillsUsed++;

    Debug.Log($"ðŸ’Š PÃ­lula usada! Sanidade: {sanity:F1} | PÃ­lulas restantes: {maxPills - pillsUsed}");
}
}
